### ISSUE TITLE
Should it be zh_CN?

### ISSUE THREAD

**Issue by ucSec** [sparkylinux/sparky-about#4]
https://github.com/sparkylinux/sparky-about/blob/bb4153002fbb8256a3041975b6e2d3332caf1c1d/bin/sparky-about#L39
Should it be zh_CN here?

**Comment by ucSec** [comment]
That's true, after I upgrade it, sparky-about's langueage is not zh_CN.

**Comment by pavroo** [comment]
yep, my mistake, thanks.

**Comment by ucSec** [comment]
SOLVED
